### ISSUE TITLE
Topology API

### ISSUE THREAD

**Issue by ztnel** [dronectl/fusion#7]
# Description
Develop fusion topology provisioner api. This system should be flexible to allow for horizontal scaling of devices and device interfaces. The should load runtime models for the available devices dynamically. All endpoints should be strictly typed and be qualified by generics to allow for autocompletion for available capabilities. Two fundamental abstractions are required to implement a dynamic topology api:
1. Devices
2. Device Interfaces

## Device
 - firmware version for capability scoping
 - hardware version for capability scoping
 - device interfaces
 - identifier for device selection api

## Interface
 - target device address
 - test platform host address
 - identifier for device interface selection api

Below is a sample topology document. This topology named `bench` describes a single node link to a `Raptor` test system with a `TCPSocket` telemetry stream and a scpi command and control channel:
```yaml
# topology.yaml
---
topology:
  name: bench
  devices:
    # esc motor and propulsion test jig
    - type: Raptor # device type qualname of class (must be an exact match)
      idn: rpt-102 # idn for registry storage ident and tagging
      hw_version: 0.0.1 # semver
      fw_version: 0.1.0 # semver
      # communication channels are device specific
      interfaces:
        - type: TCPSocket # device interface type  qualname of class (must be an exact match)
          idn: scpi
          target: 192.168.2.34:3000
        - type: TCPSocket # device interface type  qualname of class (must be an exact match)
          idn: telemetry
          target: 192.168.2.34:3010
```

By using the qualname in the type fields, fusion can automatically discover classes in particular directories and auto instantiate these instances. This makes the system easier to scale since it does not require and core loader modifications as new types are added.
